/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seek;

import java.io.IOException;
import java.util.Map;

public class App {
    private static Map<String, Integer> carsRecordMap;

    public static void main(String[] args) throws IOException {

        Input input = new FileInput(args[0]);

        carsRecordMap = input.read();

        Processor processor = new CarsProcessor(carsRecordMap);

        processor.execute();
    }

}
